sudo: required
dist: trusty
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
language: node_js

branches:
  only:
    - dev
    - master

node_js:
  - "8"
  - "node"

before_install:
  - npm i npm@^4 -g
  - npm install -g  @angular/cli

install:
  - npm install

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3

script:
  - node server/server.js &
  - ng test

after_success:
  - npm run codecov

notifications:
  email: false
