version: "3"
services:
  server:
    build:
      context: .
      dockerfile: docker/Dockerfile-server
    ports:
        - 3000:3000
    command: "npm start"

  node-latest:
    build:
      context: .
      dockerfile: docker/Dockerfile-node-latest
    volumes:
      - ./:/app/
    ports:
      - "3001:3000"
    command: "npm run docker-test-latest"

  node-9:
    build:
      context: .
      dockerfile: docker/Dockerfile-node-9
    volumes:
      - ./:/app/
    ports:
      - "3002:3000"
    command: "npm run docker-test-9"

  node-8:
    build:
      context: .
      dockerfile: docker/Dockerfile-node-8
    volumes:
      - ./:/app/
    ports:
      - "3003:3000"
    command: "npm run docker-test-8"