FROM node:latest


RUN apt-get update \
    && apt-get install -y chromium

ENV CHROME_BIN=chromium

WORKDIR /usr/src/app

COPY package*.json ./
RUN npm install karma karma-mocha chai -g
RUN npm i --save-dev karma-phantomjs-launcher
RUN npm install

COPY . .

EXPOSE 3001
